### ISSUE TITLE
Firefox closes control connection when playback is stopped

### ISSUE THREAD

**Issue by badaix** [badaix/snapweb#19]
Steps to reproduce 
- open `http://<host>:1780` in firefox
- Press play: audio starts, the Snapweb client is shown in the web UI
- Press stop: audio stops, the Snapweb client is removed from the web UI
- Press play again: audio starts, updates are not shown in web UI

In Firefox's websocket inspector and in wireshark you can see that the control connection (`ws://<host>:1780/jsonrpc`) is closed with status code 1001 when stop is pressed

**Comment by patagonaa** [comment]
I just had a quick look at this and it seems the issue is that in snapstream.ts, `stop()` calls `this.streamsocket.close();`, which in turn calls `this.streamsocket.onclose` which calls `stop()` again.

For some reason this causes firefox to close all running websockets (maybe this is also a firefox bug?).
By pure chance, #23 fixes this by not calling `stop()` in `onclose` anymore.

**Comment by patagonaa** [comment]
Actually, I dug into this deeper (trying to reproduce this to maybe report it to mozilla) and the issue **isn't** that `onclose` calls `stop()` which calls `close()` again.

The actual issue is that `stop()` in this case is not the `SnapStream.stop()` (which in this context would be `this.stop()`) but `window.stop()`, which is a global function to stop loading the current page.
On Firefox this apparently also means killing all existing websocket connections.

Still, #23 fixes this because `stop()` is no longer called in `onclose`.

**Comment by badaix** [comment]
Cool, thanks for investigating this. Even the strg+click code navigation in vs code is pointing me to `window.stop()` :facepalm:

**Comment by patagonaa** [comment]
> Cool, thanks for investigating this. Even the strg+click code navigation in vs code is pointing me to `window.stop()` 🤦

Don't worry, even as a full-time web developer these kind of issues happen sometimes (and it took me like two hours of trying to reproduce this outside of snapweb and some debugging to find it). It was just really unlucky that there was a function on the window with the exact signature you were expecting.
