### ISSUE TITLE
Issues when switching between sources of different sample rates

### ISSUE THREAD

**Issue by patagonaa** [badaix/snapweb#31]
When switching the SnapStream between different sources that have different sample rates, sound gets really broken (changes speed/pitch rapidly).

The issue seems to have been introduced with commit 1f4aa6381079f1c83f0c6cb3a07550f9b971338a, before this commit the sources could be switched without any issues.

I've tried my hand at debugging the issue and I think the issue might be the reuse of buffers with the wrong sample rate. When I set a breakpoint in the `playNext()` method in snapstream.ts, after switching sources I sometimes get buffers with a length of 3840 and 48000Hz, sometimes I get buffers with a length of 3528 and 44100Hz (the source I've switched to is 44100Hz).

**Comment by badaix** [comment]
I think the main issue is the reused AudioContext. On webkit based browsers the context must be created through user interaction, so that the browser will not start playing audio without any user input. Before this commit 1f4aa63 the context was created in a Websocket receive callback, from a different thread context, i.e. not by direct user interaction (only the thread context was started by the user).
And yes, another issue is the size of the buffers, which might be too small when switching from 48kHz to 44.1kHz.
With commit 11405c9 for non-webkit browsers the playback is stopped and the AudioContext and buffers are recreated using the correct samplerate. This means that iOS users have to start/stop playback when switching to a stream with a different sample rate. If the stream change is triggered from the web UI, then the AudioContext could be recreated even for iOS devices. But I don't own any iOS devices, so I cannot test this (best I can do is to basic checks with the webkit based Epiphany browser). Another option would be resampling of the input stream.

**Comment by patagonaa** [comment]
At least for Firefox and Chrome, this seems to work now. Can't test with iOS as I haven't got any devices either.

If there's nothing else to do here, you can close this issue.
Thank you for the quick response.
