### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by bendschs** [badaix/snapweb#48]

**Comment by bendschs** [comment]
no commits since march 21, plenty of unresolved issues?

**Comment by curiousercreative** [comment]
(It's not my repo, so take everything with a grain of salt)

Releases aren't published or tagged it seems, but you'll see in [this commit](https://github.com/badaix/snapweb/commit/f19a12a3c27d0a4fcbb1058f365f36973c09d033) there have been releases versioned by the repo owner. What are you looking for really though? Are you a snapcast user?

**Comment by bendschs** [comment]
yes, am using snapcast for a while together with mopidy/iris. one thing that i am actually still looking very much forward to ist  a working snapcast under safari (webkit) ios. This one seems to be broken for quite some time now (see the open [or closed, due to inactivity?) issues for that.

i had version 5.0 installed for a long time, safari issue is not resolved in that one.

in general it just does not seem that the project ist still being maintained but maybe that's just my impression.

**Comment by kingosticks** [comment]
I think the readme already gives a fair impression (my emphasis):

> This web client is the author's first JavaScript/TypeScript project and is rather *a proof of concept* for the Snapserver's [WebSocket API](https://github.com/badaix/snapcast/blob/master/doc/json_rpc_api/v2_0_0.md).
*Since my time and my web development skills are limited, pull requests are highly appreciated.* Please check the list of [open issues](https://github.com/badaix/snapweb/issues).


And for the Safari issue [it's pretty clear](https://github.com/badaix/snapweb/issues/18):

> I don't own any iDevices to fix this, so I've labelled this with "help wanted".

Users need to help with any project's maintenance, in this case they also need to help with fixes in some cases also. This is very reasonable.

**Comment by curiousercreative** [comment]
@bendschs if you read to the end of the README, you'll find the repo owner is not a frontend web engineer and I don't think they own any iOS or macOS devices. That makes this more of a DIY or community project. It's not dead, but the repo owner doesn't actively develop it despite the bugs.

If you're unable to contribute as an engineer, you might try contributing efforts testing proposed fixes like this one: https://github.com/badaix/snapweb/pull/45

**Comment by curiousercreative** [comment]
I'd recommend closing this issue as it does nothing to further any efforts to improve this project, but please consider engaging directly on the issues themselves.

**Comment by badaix** [comment]
At least since March 2023, two month before you raised this question, there was quite active development happening in the React branch. 
Since React and frontend development in general is quite new to me and since this is just a spare time project, which is a sub-project to Snapcast, my main spare time project, it is not developed in a pace of a commercial full time project.
I'm happily using the React version for at least 6 month, but I'm still afraid of introducing bugs and regressions. You are always welcome to test development snapshots. Starting with version 0.6.0 everything is properly versionized and packaged and can easily be deployed by extracting a zip archive or installing a debian package.
